### ISSUE TITLE
Customize the highlight syntax manually

### ISSUE THREAD

**Issue by bscan** [iuyoy/highlight-string-code#4]
Hi, this extension is great for VSCode, thanks! For SQL, is it possible to add a setting to disable the highlighting on UPPERCASE statements? I often read existing code with embedded SQL that does not have semicolon endings. For these cases, the highlighting will be incorrect for the rest of the code. Python example below. 

```python
print(2) # Highlighted correctly

query = """
SELECT *
FROM db.tbl
"""

print(2) # Not highlighted correctly
```

**Comment by iuyoy** [comment]
Hi @bscan,
This extension implements the highlighting by [syntax highlight method](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) , which means there is only a JSON config for highlight rules, and any function of `setting` should be implemented in TS or JS. So currently, any rule cannot be disabled by settings.

There is a manual way to disable it:
1. locate to the extension install folder in your computer.
2. delete highlighted part of the following picture in `syntaxes/highlight-string-code.json`.
![image](https://user-images.githubusercontent.com/11738832/97805511-9a548c80-1c91-11eb-8c59-1658137012aa.png)
3. reload this extension or restart VSCode to make it work.

Also, I have an idea to modify the rule JSON config by a TS/JS script, but I am not sure if it can work. Please excuse me for the slow development, because my current work has less relation with SQL or other embedded languages.

**Comment by Nu11u5** [comment]
The SQL uppercase rule is triggered by any match, even if the keyword is in the middle of another word.  Additionally, the text *must* include a `;` semicolon for the matching to end.

*(Example using PowerShell, where I encountered the issue, but it should affect any language)*

![image](https://user-images.githubusercontent.com/617690/210876696-ae193352-8f59-474f-8b32-3a3e3e0a1434.png)

While the SQL keyword matching is useful for inline text it is more likely to cause problems than solve them as implemented.

At the very least, the SQL keyword rule regex should match if the keyword is preceded by a word boundary metacharacter - this would fix issues where the keyword appears at the end of another word in a non-SQL statement.  However, this is only an edge case.

For best experience, the SQL keyword rule should be removed completely.  SQL syntax highlighting can still be achieved using multiline text with `--beginsql` / `--endsql` comments.

**Comment by iuyoy** [comment]
> The SQL uppercase rule is triggered by any match, even if the keyword is in the middle of another word. Additionally, the text _must_ include a `;` semicolon for the matching to end.
> 
> _(Example using PowerShell, where I encountered the issue, but it should affect any language)_
> 
> ![image](https://user-images.githubusercontent.com/617690/210876696-ae193352-8f59-474f-8b32-3a3e3e0a1434.png)
> 
> While the SQL keyword matching is useful for inline text it is more likely to cause problems than solve them as implemented.
> 
> At the very least, the SQL keyword rule regex should match if the keyword is preceded by a word boundary metacharacter - this would fix issues where the keyword appears at the end of another word in a non-SQL statement. However, this is only an edge case.
> 
> For best experience, the SQL keyword rule should be removed completely. SQL syntax highlighting can still be achieved using multiline text with `--beginsql` / `--endsql` comments.

In my view, adding a `;` is much easier than multiline text to highlight a sql.
If you prefer to disable this feature, the above response can help.

**Comment by Nu11u5** [comment]
> In my view, adding a ; is much easier than multiline text to highlight a sql.

In case there is a misunderstanding - adding a `;` cannot not fix this issue, since the code is not even SQL.  None of the code shown is SQL yet the extension highlights it anyway.

**Comment by iuyoy** [comment]
> > In my view, adding a ; is much easier than multiline text to highlight a sql.
> 
> In case there is a misunderstanding - adding a `;` cannot not fix this issue, since the code is not even SQL. None of the code shown is SQL yet the extension highlights it anyway.

I understand. I was just explaining why I added the SQL keyword rule. Due to the limitations mentioned in #6, this is the best compromise I can offer. Different people have their own requirements, so I recommend editing the syntaxes to solve your problem.
